Repository connect-foundation/2019-18, pull requests merged in 2019-12, with the labels that each got.

#121 Feature/jmj/infinite scroll
  client/.storybook/addons.js
  client/.storybook/config.js
  client/package-lock.json
  client/package.json
  client/src/components/Card/index.tsx
  client/src/components/FeedContainer/index.tsx
  client/src/components/FeedWallpapers/index.tsx
  client/src/components/FeedWallpapers/styles.ts
  client/src/components/FeedWallpapers/type.ts
  client/src/components/FeedWorks/index.tsx
  client/src/components/FeedWorks/styles.ts
  client/src/components/FeedWorks/type.ts
  client/src/components/UploadImage/index.tsx
  client/src/components/UploadImage/style.tsx
  client/src/components/UploadImage/type.ts
  client/src/components/Upload_detail_Popup/index.tsx
  client/src/components/WorksDetail/index.tsx
  client/src/containers/WorkDetailContainer.tsx
  client/src/hooks/useGetFeedList.ts
  client/src/utils/constants.ts
  client/stories/0-Welcome.stories.js
  client/stories/1-Button.stories.js
  server/controllers/feeds.ts
  server/controllers/upload.ts
  server/customType/user.ts
  server/middleware/jwt.ts
  server/package-lock.json
  server/package.json
  server/routes/feed.route.ts
  server/routes/upload.route.ts
  server/services/feed.ts
  server/services/user.ts
  server/utils/messages.ts
Labels: API, BE, enhancement

#174 Feature/junow/modify work detail design
  client/package-lock.json
  client/package.json
  client/src/components/Card/MusicCard/styles.ts
  client/src/components/Card/WorksCard/styles.ts
  client/src/components/Card/WorksCard/types.ts
  client/src/components/Comment/index.tsx
  client/src/components/Comment/styles.ts
  client/src/components/FeedWallpapers/index.tsx
  client/src/components/FeedWallpapers/type.ts
  client/src/components/FeedWorks/index.tsx
  client/src/components/FeedWorks/type.ts
  client/src/components/WorksDetail/index.tsx
  client/src/components/WorksDetail/styles.ts
  client/src/components/WorksDetail/types.ts
  client/src/modules/feed/types.ts
  client/src/style/globalStyle.ts
  client/src/style/theme.ts
  client/src/utils/check.ts
  client/src/utils/index.ts
  server/controllers/feeds.ts
  server/package-lock.json
Labels: BE, FE

#175 Feature/junow/set socket url
  client/package-lock.json
  client/package.json
  client/src/components/FeedNavigator/styles.ts
  client/src/components/Header/HeaderLeft/styles.ts
  client/src/components/Header/index.tsx
  client/src/components/Header/styles.ts
  client/src/socket/index.ts
  client/src/style/globalStyle.ts
  client/src/utils/constants.ts
Labels: FE

#186 Feature/junow/notifications through socket
  client/src/components/Alarm/NotificationItem/index.tsx
  client/src/components/Alarm/NotificationItem/styles.ts
  client/src/components/Alarm/Notifications/index.tsx
  client/src/components/Alarm/Notifications/styles.ts
  client/src/components/Alarm/index.tsx
  client/src/components/Alarm/styles.ts
  client/src/components/MusicDetail/index.tsx
  client/src/components/MusicDetail/styles.ts
  client/src/components/MusicDetail/types.ts
  client/src/components/UploadMain/index.tsx
  client/src/components/UploadMusic/Modal/styles.tsx
  client/src/components/UploadMusic/MusicUploader/index.tsx
  client/src/components/UploadMusic/MusicUploader/styles.ts
  client/src/components/UploadMusic/ToolBox/index.tsx
  client/src/components/UploadMusic/ToolBox/styles.ts
  client/src/components/UploadMusic/index.tsx
  client/src/components/UploadMusic/styles.ts
  client/src/containers/MusicDetailContainer.tsx
  client/src/containers/NotificationContainer.tsx
  client/src/containers/UploadMusicContainer.tsx
  client/src/modules/notification/types.ts
  client/src/socket/index.ts
  client/src/utils/check.ts
  client/src/utils/constants.ts
  server/controllers/feeds.ts
  server/routes/feed.route.ts
  server/services/feed.ts
  server/services/upload.ts
  server/socket/index.ts
Labels: FE

#190 [Modified] axios-instance
  client/src/containers/FeedWorkContainer.tsx
  client/src/modules/loginuser/index.ts
  client/src/utils/request.ts
  server/middleware/authByJWT.ts
Labels: API, FE

#193 Feature/jmj lgh/view abusing middleware
  client/package-lock.json
  server/controllers/feeds.ts
  server/middleware/abusingDetector.ts
  server/middleware/viewUpdate.ts
  server/package-lock.json
  server/routes/feed.route.ts
  server/services/feed.ts
Labels: REFACTORING

#194 [Fixed] 로그인 안한 사용자도 다운로드 버튼을 볼 수 있음
  client/src/basics/PURPLE_Button/style.ts
  client/src/commons/Popup_warn/style.ts
  client/src/components/Preview/style.tsx
  client/src/components/UploadImage/index.tsx
  client/src/components/UploadImage/style.tsx
  client/src/components/UploadMain/style.tsx
  client/src/components/Upload_detail_Popup/index.tsx
  client/src/components/Upload_detail_Popup/style.ts
  client/src/components/WorksDetail/index.tsx
  client/src/utils/constants.ts
Labels: REFACTORING

#196 [Modified] 이미지속성 모두 background-image로 대체
  client/src/components/MusicPlayer/styles.ts
  client/src/components/WorksDetail/index.tsx
  client/src/components/WorksDetail/styles.ts
Labels: REFACTORING

#197 [Modified] 알람메시지에 링크 추가
  client/src/components/Alarm/NotificationItem/index.tsx
  client/src/components/Alarm/Notifications/index.tsx
  client/src/modules/notification/types.ts
Labels: REFACTORING

#200 [Refactor] axios instance 함수 사용
  client/src/components/Alarm/Notifications/index.tsx
  client/src/components/UploadMusic/index.tsx
  client/src/containers/MusicDetailContainer.tsx
  client/src/containers/NotificationContainer.tsx
  client/src/containers/UploadMusicContainer.tsx
  client/src/containers/WorkDetailContainer.tsx
  client/src/modules/loginuser/index.ts
  client/src/utils/request.ts
Labels: REFACTORING

#205 Create LICENSE
  LICENSE
Labels: documentation

#208 Hotfix/junow/wallpaper download
  client/src/components/WorksDetail/index.tsx
  client/src/components/WorksDetail/styles.ts
  client/src/components/WorksDetail/types.ts
  client/src/utils/index.ts
  server/controllers/feeds.ts
  server/redis/index.ts
  server/utils/constant.ts
  server/utils/imageDownload.ts
Labels: enhancement

#212 [Hotfix] 음악 업로드 소켓 알림 추가
  client/src/components/Alarm/Notifications/index.tsx
  server/controllers/upload.ts
Labels: BE, FE, enhancement

#211 Reviewed/jmj/week5
  client/src/components/Header/HeaderRight/HeaderGreeting/index.tsx
  client/src/components/Portfolio/index.tsx
  client/src/components/PortfolioForm/index.tsx
  client/src/components/PortfolioForm/style.tsx
  client/src/components/PortfolioForm/types.ts
  client/src/components/UploadImage/index.tsx
  client/src/containers/PortfolioFormContainer.tsx
  client/src/modules/login/action.ts
  client/src/modules/login/reducer.ts
  client/src/modules/login/types.ts
  client/src/utils/request.ts
  server/controllers/user.ts
  server/routes/user.route.ts
  server/services/user.ts
  server/utils/constant.ts
Labels: REFACTORING

#207 [Midified] seed data 변경
  server/app.ts
  server/seed/ids.ts
  server/seed/image.ts
  server/seed/index.ts
  server/seed/music.ts
  server/seed/user.ts
  server/seed/wallpaper.ts
  server/seed/work_image.ts
  server/seed/work_music.ts
Labels: architecture, enhancement
